In [2]:
import os
import re
from collections import defaultdict

import torch
import numpy as np
import pandas as pd
from transformers import pipeline

from models import Bleurt, Mpnet, ModernBERT, ModernBERT_v2, ModelInput

torch.set_float32_matmul_precision("high")
os.environ["TOKENIZERS_PARALLELISM"] = "true"

In [3]:
mb_path = "/home/jovyan/active-projects/itell-question-generation/results/modernbert_authentic_multirc"
mb_w_reference_answer_path = "/home/jovyan/active-projects/itell-question-generation/results/modernbert_authentic_multirc_with_reference_with_label"

pipes = {
    "Mpnet_pipe": Mpnet(),
    "Bleurt_pipe": Bleurt(),
    "ModernBERT_pipe": ModernBERT(mb_path),
    "ModernBERT_with_reference": ModernBERT_v2(mb_w_reference_answer_path),
}

Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda

In [4]:
responses = pd.read_csv("../../bin/2025-09-09T21-23_export.csv", index_col=0)
content = pd.read_csv("../../data/cri_questions2.csv")
df = responses.merge(content, how="inner", on=["chunk_slug", "page_slug"]).rename(
    columns={
        "text": "candidate",
        "answer": "reference",
        "chunk_text": "text",
    }
)
df

,candidate,score,condition,user_id,page_slug,chunk_slug,is_passed,chapter,created_at,volume_title,volume_slug,page_title,chunk_header,text,question,reference
0,khgkhghj,2.171278,stairs,fhdqbtxevjpxteuwt4iu3u7e2m,the-u-s-constitution,Supreme-Law-of-the-Land-4459,True,0,2025-09-08T22:14:41.667Z,"One Nation, One People: The USCIS Civics Test ...",one-nation-one-people-the-uscis-civics-test-te...,Chapter 1: The U.S. Constitution,Supreme Law of the Land,The sixth section of the Constitution says the...,What does the sixth section of the Constitutio...,The Constitution is the supreme law of the lan...
1,the supreme law of the land,2.000000,stairs,wf5jicpb5uon42yzcgjpptpzyu,the-u-s-constitution,Supreme-Law-of-the-Land-4459,True,0,2025-09-04T22:07:47.238Z,"One Nation, One People: The USCIS Civics Test ...",one-nation-one-people-the-uscis-civics-test-te...,Chapter 1: The U.S. Constitution,Supreme Law of the Land,The sixth section of the Constitution says the...,What does the sixth section of the Constitutio...,The Constitution is the supreme law of the lan...
2,I don't know,1.812920,stairs,fhdqbtxevjpxteuwt4iu3u7e2m,the-u-s-constitution,State-Governments-4457,False,0,2025-09-08T22:13:06.217Z,"One Nation, One People: The USCIS Civics Test ...",one-nation-one-people-the-uscis-civics-test-te...,Chapter 1: The U.S. Constitution,State Governments,The fourth section of the Constitution explain...,What is the role of the executive branch in a ...,The person in charge of the executive branch f...
3,The role of the executive branch is enforce fe...,2.778327,stairs,ci7hvzzqif5lhd4becodqngqye,the-u-s-constitution,State-Governments-4457,True,0,2025-09-08T03:42:18.481Z,"One Nation, One People: The USCIS Civics Test ...",one-nation-one-people-the-uscis-civics-test-te...,Chapter 1: The U.S. Constitution,State Governments,The fourth section of the Constitution explain...,What is the role of the executive branch in a ...,The person in charge of the executive branch f...
4,a,2.000000,stairs,ezc4c5yzimt7izgd3ugov2nyma,the-u-s-constitution,State-Governments-4457,True,0,2025-09-03T15:29:57.897Z,"One Nation, One People: The USCIS Civics Test ...",one-nation-one-people-the-uscis-civics-test-te...,Chapter 1: The U.S. Constitution,State Governments,The fourth section of the Constitution explain...,What is the role of the executive branch in a ...,The person in charge of the executive branch f...
5,n,0.000000,stairs,ezc4c5yzimt7izgd3ugov2nyma,the-u-s-constitution,State-Governments-4457,True,0,2025-09-03T15:29:51.531Z,"One Nation, One People: The USCIS Civics Test ...",one-nation-one-people-the-uscis-civics-test-te...,Chapter 1: The U.S. Constitution,State Governments,The fourth section of the Constitution explain...,What is the role of the executive branch in a ...,The person in charge of the executive branch f...
6,1776,2.631567,stairs,i6iirxwoh4e3bj4pkzlxyeobse,the-u-s-constitution,The-US-Constitution-4445,True,0,2025-09-08T08:06:55.561Z,"One Nation, One People: The USCIS Civics Test ...",one-nation-one-people-the-uscis-civics-test-te...,Chapter 1: The U.S. Constitution,The U.S. Constitution,"In this chapter, you will learn about:\n\nThe ...",When was the U.S. Constitution written?,The U.S. Constitution was written in 1787.
7,dasd,2.403645,stairs,6aadzk7jqpgmu4fpa44ajcxfze,the-u-s-constitution,The-US-Constitution-4445,True,0,2025-09-05T17:51:29.110Z,"One Nation, One People: The USCIS Civics Test ...",one-nation-one-people-the-uscis-civics-test-te...,Chapter 1: The U.S. Constitution,The U.S. Constitution,"In this chapter, you will learn about:\n\nThe ...",When was the U.S. Constitution written?,The U.S. Constitution was written in 1787.
8,1787,2.000000,stairs,sievio4tkp2lqjadtpracywgtq,the-u-s-constitution,The-US-Constitution-4445,True,0,2025-09-04T22:02:12.351Z,"One Nation, One People: The USCIS Civics Test ...",one-nation-one-people-the-uscis-civics-test-te...,Chapter 1: The U.S. Constitution,The U.S. Constitution,"In this chapter, you will learn about:\n\nThe ...",When was the U.S. Constitution written?,The U.S. Constitution was written in 1787.
9,in the year alkjdf,0.000000,stairs,sievio4tkp2lqjadtpracywgtq,the-u-s-constitution,The-US-Constitution-4445,True,0,2025-09-04T22:01:35.087Z,"One Nation, One People: The USCIS Civics Test ...",one-nation-one-people-the-uscis-civics-test-te...,Chapter 1: The U.S. Constitution,The U.S. Constitution,"In this chapter, you will learn about:\n\nThe ...",When was the U.S. Constitution written?,The U.S. Constitution was written in 1787.
10,in the year 1787,2.000000,stairs,sievio4tkp2lqjadtpracywgtq,the-u-s-constitution,The-US-Constitution-4445,True,0,2025-09-04T22:01:05.395Z,"One Nation, One People: The USCIS Civics Test ...",one-nation-one-people-the-uscis-civics-test-te...,Chapter 1: The U.S. Constitution,The U.S. Constitution,"In this chapter, you will learn about:\n\nThe ...",When was the U.S. Constitution written?,The U.S. Constitution was written in 1787.
11,in the year 1778,0.000000,stairs,sievio4tkp2lqjadtpracywgtq,the-u-s-constitution,The-US-Constitution-4445,True,0,2025-09-04T22:00:46.378Z,"One Nation, One People: The USCIS Civics Test ...",one-nation-one-people-the-uscis-civics-test-te...,Chapter 1: The U.S. Constitution,The U.S. Constitution,"In this chapter, you will learn about:\n\nThe ...",When was the U.S. Constitution written?,The U.S. Constitution was written in 1787.
12,1778,0.000000,stairs,sievio4tkp2lqjadtpracywgtq,the-u-s-constitution,The-US-Constitution-4445,True,0,2025-09-04T21:59:58.592Z,"One Nation, One People: The USCIS Civics Test ...",one-nation-one-people-the-uscis-civics-test-te...,Chapter 1: The U.S. Constitution,The U.S. Constitution,"In this chapter, you will learn about:\n\nThe ...",When was the U.S. Constitution written?,The U.S. Constitution was written in 1787.
13,1780,0.000000,stairs,sievio4tkp2lqjadtpracywgtq,the-u-s-constitution,The-US-Constitution-4445,True,0,2025-09-04T21:59:42.454Z,"One Nation, One People: The USCIS Civics Test ...",one-nation-one-people-the-uscis-civics-test-te...,Chapter 1: The U.S. Constitution,The U.S. Constitution,"In this chapter, you will learn about:\n\nThe ...",When was the U.S. Constitution written?,The U.S. Constitution was written in 1787.
14,1760,0.000000,stairs,sievio4tkp2lqjadtpracywgtq,the-u-s-constitution,The-US-Constitution-4445,True,0,2025-09-04T21:59:33.160Z,"One Nation, One People: The USCIS Civics Test ...",one-nation-one-people-the-uscis-civics-test-te...,Chapter 1: The U.S. Constitution,The U.S. Constitution,"In this chapter, you will learn about:\n\nThe ...",When was the U.S. Constitution written?,The U.S. Constitution was written in 1787.
15,seventeen hundred and eighty seven,1.000000,stairs,i5elwnv4rzehfxkqz7gkybn7uu,the-u-s-constitution,The-US-Constitution-4445,True,0,2025-09-04T15:34:41.318Z,"One Nation, One People: The USCIS Civics Test ...",one-nation-one-people-the-uscis-civics-test-te...,Chapter 1: The U.S. Constitution,The U.S. Constitution,"In this chapter, you will learn about:\n\nThe ...",When was the U.S. Constitution written?,The U.S. Constitution was written in 1787.
16,1787,2.000000,stairs,i5elwnv4rzehfxkqz7gkybn7uu,the-u-s-constitution,The-US-Constitution-4445,True,0,2025-09-04T15:33:28.875Z,"One Nation, One People: The USCIS Civics Test ...",one-nation-one-people-the-uscis-civics-test-te...,Chapter 1: The U.S. Constitution,The U.S. Constitution,"In this chapter, you will learn about:\n\nThe ...",When was the U.S. Constitution written?,The U.S. Constitution was written in 1787.
17,38 out of the 50 states.,2.862408,stairs,i6iirxwoh4e3bj4pkzlxyeobse,the-u-s-constitution,Changing-The-Constitution-4458,True,0,2025-09-08T07:39:24.647Z,"One Nation, One People: The USCIS Civics Test ...",one-nation-one-people-the-uscis-civics-test-te...,Chapter 1: The U.S. Constitution,Changing The Constitution,The fifth section of the Constitution explains...,How many states must approve an amendment for ...,38 out of the 50 states.
18,38,2.279422,stairs,i6iirxwoh4e3bj4pkzlxyeobse,the-u-s-constitution,Changing-The-Constitution-4458,True,0,2025-09-08T07:33:18.272Z,"One Nation, One People: The USCIS Civics Test ...",one-nation-one-people-the-uscis-civics-test-te...,Chapter 1: The U.S. Constitution,Changing The Constitution,The fifth section of the Constitution explains...,How many states must approve an amendment for ...,38 out of the 50 states.
19,38 states out of 50,2.773945,stairs,ci7hvzzqif5lhd4becodqngqye,the-u-s-constitution,Changing-The-Constitution-4458,True,0,2025-09-08T03:42:50.249Z,"One Nation, One People: The USCIS Civics Test ...",one-nation-one-people-the-uscis-civics-test-te...,Chapter 1: The U.S. Constitution,Changing The Constitution,The fifth section of the Constitution explains...,How many states must approve an amendment for ...,38 out of the 50 states.
20,38 states,2.000000,stairs,wf5jicpb5uon42yzcgjpptpzyu,the-u-s-constitution,Changing-The-Constitution-4458,True,0,2025-09-04T22:07:35.581Z,"One Nation, One People: The USCIS Civics Test ...",one-nation-one-people-the-uscis-civics-test-te...,Chapter 1: The U.S. Constitution,Changing The Constitution,The fifth section of the Constitution explains...,How many states must approve an amendment for ...,38 out of the 50 states.
21,"It reflects the ideas of self-government, whic...",3.520907,stairs,ci7hvzzqif5lhd4becodqngqye,the-u-s-constitution,We-The-People-4447,True,0,2025-09-08T03:37:11.907Z,"One Nation, One People: The USCIS Civics Test ...",one-nation-one-people-the-uscis-civics-test-te...,Chapter 1: The U.S. Constitution,We The People,The beginning of the Constitution is called th...,What is the significance of the first three wo...,"The first three words, 'We the people', signif..."
22,make the president follow the rule of law,1.000000,stairs,sievio4tkp2lqjadtpracywgtq,chapter-3-the-executive-branch,The-Executive-Branch-4752,True,0,2025-09-05T02:32:50.426Z,"One Nation, One People: The USCIS Civics Test ...",one-nation-one-people-the-uscis-civics-test-te...,Chapter 3: The Executive Branch,The Executive Branch,"In this chapter, you will learn about:\n\nThe ...",What is the purpose of the Executive Branch ac...,The purpose of the Executive Branch is to prot...
23,house of rep and senate,2.000000,stairs,sievio4tkp2lqjadtpracywgtq,chapter-2-legislative-branch,The-Legislative-Branch-Congress-4729,True,0,2025-09-05T02:16:24.695Z,"One Nation, One People: The USCIS Civics Test ...",one-nation-one-people-the-uscis-civics-test-te...,Chapter 2: The Legislative Branch,The Legislative Branch (Congress),"In this chapter, you will learn about:\n\nThe ...",What are the two parts of the U.S. Congress?,The House of Representatives and the Senate.
24,"They have a higher, bigger population so they ...",2.000000,stairs,wf5jicpb5uon42yzcgjpptpzyu,chapter-2-legislative-branch,The-House-of-Representatives-4730,True,0,2025-09-04T22:11:33.914Z,"One Nation, One People: The USCIS Civics Test ...",one-nation-one-people-the-uscis-civics-test-te...,Chapter 2: The Legislative Branch,The House of Representatives,Voting Members of the House of Representatives...,Why do some states have more representatives i...,Because states that have more people have more...
25,judicial legsilative executive,2.000000,stairs,sievio4tkp2lqjadtpracywgtq,the-u-s-constitution,The-Federal-Government-4448,True,0,2025-09-04T22:09:57.638Z,"One Nation, One People: The USCIS Civics Test ...",one-nation-one-people-the-uscis-civics-test-te...,Chapter 1: The U.S. Constitution,The Federal Government,The Three Branches of Government\n\nThe first ...,What are the three branches of the U.S. govern...,"The Legislative Branch, the Executive Branch, ..."
26,justice legsilative executive,0.000000,stairs,sievio4tkp2lqjadtpracywgtq,the-u-s-constitution,The-Federal-Government-4448,True,0,2025-09-04T22:09:51.798Z,"One Nation, One People: The USCIS Civics Test ...",one-nation-one-people-the-uscis-civics-test-te...,Chapter 1: The U.S. Constitution,The Federal Government,The Three Branches of Government\n\nThe first ...,What are the three branches of the U.S. govern...,"The Legislative Branch, the Executive Branch, ..."
27,justice legal executive,1.000000,stairs,sievio4tkp2lqjadtpracywgtq,the-u-s-constitution,The-Federal-Government-4448,True,0,2025-09-04T22:09:17.405Z,"One Nation, One People: The USCIS Civics Test ...",one-nation-one-people-the-uscis-civics-test-te...,Chapter 1: The U.S. Constitution,The Federal Government,The Three Branches of Government\n\nThe first ...,What are the three branches of the U.S. govern...,"The Legislative Branch, the Executive Branch, ..."
28,justice legal exec,0.000000,stairs,sievio4tkp2lqjadtpracywgtq,the-u-s-constitution,The-Federal-Government-4448,True,0,2025-09-04T22:09:12.082Z,"One Nation, One People: The USCIS Civics Test ...",one-nation-one-people-the-uscis-civics-test-te...,Chapter 1: The U.S. Constitution,The Federal Government,The Three Branches of Government\n\nThe first ...,What are the three branches of the U.S. govern...,"The Legislative Branch, the Executive Branch, ..."
29,i dunno,0.000000,stairs,sievio4tkp2lqjadtpracywgtq,the-u-s-constitution,The-Federal-Government-4448,True,0,2025-09-04T22:09:01.628Z,"One Nation, One People: The USCIS Civics Test ...",one-nation-one-people-the-uscis-civics-test-te...,Chapter 1: The U.S. Constitution,The Federal Government,The Three Branches of Government\n\nThe first ...,What are the three branches of the U.S. govern...,"The Legislative Branch, the Executive Branch, ..."
30,asfkjh,0.000000,stairs,sievio4tkp2lqjadtpracywgtq,the-u-s-constitution,The-Federal-Government-4448,True,0,2025-09-04T22:08:58.391Z,"One Nation, One People: The USCIS Civics Test ...",one-nation-one-people-the-uscis-civics-test-te...,Chapter 1: The U.S. Constitution,The Federal Government,The Three Branches of Government\n\nThe first ...,What are the three branches of the U.S. govern...,"The Legislative Branch, the Executive Branch, ..."

In [5]:
def score(df, pipes, label_key="labels"):
    all_preds = defaultdict(list)

    for name, pipe in pipes.items():
        for ex in df.to_dict("records"):
            model_input = ModelInput.from_dict(ex)
            pred = pipe(model_input)
            all_preds[name].append(pred)

    return all_preds


all_preds = score(df, pipes)

You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

In [6]:
for model_name, preds in all_preds.items():
    df[model_name] = preds

df["ensemble"] = df["Mpnet_pipe"] + df["Bleurt_pipe"]
df

,candidate,score,condition,user_id,page_slug,chunk_slug,is_passed,chapter,created_at,volume_title,...,page_title,chunk_header,text,question,reference,Mpnet_pipe,Bleurt_pipe,ModernBERT_pipe,ModernBERT_with_reference,ensemble
0,khgkhghj,2.171278,stairs,fhdqbtxevjpxteuwt4iu3u7e2m,the-u-s-constitution,Supreme-Law-of-the-Land-4459,True,0,2025-09-08T22:14:41.667Z,"One Nation, One People: The USCIS Civics Test ...",...,Chapter 1: The U.S. Constitution,Supreme Law of the Land,The sixth section of the Constitution says the...,What does the sixth section of the Constitutio...,The Constitution is the supreme law of the lan...,0,0,2.170975,1.770094,0
1,the supreme law of the land,2.000000,stairs,wf5jicpb5uon42yzcgjpptpzyu,the-u-s-constitution,Supreme-Law-of-the-Land-4459,True,0,2025-09-04T22:07:47.238Z,"One Nation, One People: The USCIS Civics Test ...",...,Chapter 1: The U.S. Constitution,Supreme Law of the Land,The sixth section of the Constitution says the...,What does the sixth section of the Constitutio...,The Constitution is the supreme law of the lan...,1,1,2.628478,3.115588,2
2,I don't know,1.812920,stairs,fhdqbtxevjpxteuwt4iu3u7e2m,the-u-s-constitution,State-Governments-4457,False,0,2025-09-08T22:13:06.217Z,"One Nation, One People: The USCIS Civics Test ...",...,Chapter 1: The U.S. Constitution,State Governments,The fourth section of the Constitution explain...,What is the role of the executive branch in a ...,The person in charge of the executive branch f...,0,0,1.813844,1.492057,0
3,The role of the executive branch is enforce fe...,2.778327,stairs,ci7hvzzqif5lhd4becodqngqye,the-u-s-constitution,State-Governments-4457,True,0,2025-09-08T03:42:18.481Z,"One Nation, One People: The USCIS Civics Test ...",...,Chapter 1: The U.S. Constitution,State Governments,The fourth section of the Constitution explain...,What is the role of the executive branch in a ...,The person in charge of the executive branch f...,0,1,2.777066,2.599865,1
4,a,2.000000,stairs,ezc4c5yzimt7izgd3ugov2nyma,the-u-s-constitution,State-Governments-4457,True,0,2025-09-03T15:29:57.897Z,"One Nation, One People: The USCIS Civics Test ...",...,Chapter 1: The U.S. Constitution,State Governments,The fourth section of the Constitution explain...,What is the role of the executive branch in a ...,The person in charge of the executive branch f...,1,1,1.470363,1.832988,2
5,n,0.000000,stairs,ezc4c5yzimt7izgd3ugov2nyma,the-u-s-constitution,State-Governments-4457,True,0,2025-09-03T15:29:51.531Z,"One Nation, One People: The USCIS Civics Test ...",...,Chapter 1: The U.S. Constitution,State Governments,The fourth section of the Constitution explain...,What is the role of the executive branch in a ...,The person in charge of the executive branch f...,0,0,1.295934,1.149224,0
6,1776,2.631567,stairs,i6iirxwoh4e3bj4pkzlxyeobse,the-u-s-constitution,The-US-Constitution-4445,True,0,2025-09-08T08:06:55.561Z,"One Nation, One People: The USCIS Civics Test ...",...,Chapter 1: The U.S. Constitution,The U.S. Constitution,"In this chapter, you will learn about:\n\nThe ...",When was the U.S. Constitution written?,The U.S. Constitution was written in 1787.,0,0,2.631322,1.983289,0
7,dasd,2.403645,stairs,6aadzk7jqpgmu4fpa44ajcxfze,the-u-s-constitution,The-US-Constitution-4445,True,0,2025-09-05T17:51:29.110Z,"One Nation, One People: The USCIS Civics Test ...",...,Chapter 1: The U.S. Constitution,The U.S. Constitution,"In this chapter, you will learn about:\n\nThe ...",When was the U.S. Constitution written?,The U.S. Constitution was written in 1787.,0,0,2.402570,1.395974,0
8,1787,2.000000,stairs,sievio4tkp2lqjadtpracywgtq,the-u-s-constitution,The-US-Constitution-4445,True,0,2025-09-04T22:02:12.351Z,"One Nation, One People: The USCIS Civics Test ...",...,Chapter 1: The U.S. Constitution,The U.S. Constitution,"In this chapter, you will learn about:\n\nThe ...",When was the U.S. Constitution written?,The U.S. Constitution was written in 1787.,1,1,2.987468,2.697045,2
9,in the year alkjdf,0.000000,stairs,sievio4tkp2lqjadtpracywgtq,the-u-s-constitution,The-US-Constitution-4445,True,0,2025-09-04T22:01:35.087Z,"One Nation, One People: The USCIS Civics Test ...",...,Chapter 1: The U.S. Constitution,The U.S. Constitution,"In this chapter, you will learn about:\n\nThe ...",When was the U.S. Constitution written?,The U.S. Constitution was written in 1787.,0,0,1.546475,1.271996,0
10,in the year 1787,2.000000,stairs,sievio4tkp2lqjadtpracywgtq,the-u-s-constitution,The-US-Constitution-4445,True,0,2025-09-04T22:01:05.395Z,"One Nation, One People: The USCIS Civics Test ...",...,Chapter 1: The U.S. Constitution,The U.S. Constitution,"In this chapter, you will learn about:\n\nThe ...",When was the U.S. Constitution written?,The U.S. Constitution was written in 1787.,1,1,2.426890,2.365596,2
11,in the year 1778,0.000000,stairs,sievio4tkp2lqjadtpracywgtq,the-u-s-constitution,The-US-Constitution-4445,True,0,2025-09-04T22:00:46.378Z,"One Nation, One People: The USCIS Civics Test ...",...,Chapter 1: The U.S. Constitution,The U.S. Constitution,"In this chapter, you will learn about:\n\nThe ...",When was the U.S. Constitution written?,The U.S. Constitution was written in 1787.,0,0,2.047097,1.655477,0
12,1778,0.000000,stairs,sievio4tkp2lqjadtpracywgtq,the-u-s-constitution,The-US-Constitution-4445,True,0,2025-09-04T21:59:58.592Z,"One Nation, One People: The USCIS Civics Test ...",...,Chapter 1: The U.S. Constitution,The U.S. Constitution,"In this chapter, you will learn about:\n\nThe ...",When was the U.S. Constitution written?,The U.S. Constitution was written in 1787.,0,0,2.592768,1.892121,0
13,1780,0.000000,stairs,sievio4tkp2lqjadtpracywgtq,the-u-s-constitution,The-US-Constitution-4445,True,0,2025-09-04T21:59:42.454Z,"One Nation, One People: The USCIS Civics Test ...",...,Chapter 1: The U.S. Constitution,The U.S. Constitution,"In this chapter, you will learn about:\n\nThe ...",When was the U.S. Constitution written?,The U.S. Constitution was written in 1787.,0,0,2.551407,1.859797,0
14,1760,0.000000,stairs,sievio4tkp2lqjadtpracywgtq,the-u-s-constitution,The-US-Constitution-4445,True,0,2025-09-04T21:59:33.160Z,"One Nation, One People: The USCIS Civics Test ...",...,Chapter 1: The U.S. Constitution,The U.S. Constitution,"In this chapter, you will learn about:\n\nThe ...",When was the U.S. Constitution written?,The U.S. Constitution was written in 1787.,0,0,2.676636,1.930154,0
15,seventeen hundred and eighty seven,1.000000,stairs,i5elwnv4rzehfxkqz7gkybn7uu,the-u-s-constitution,The-US-Constitution-4445,True,0,2025-09-04T15:34:41.318Z,"One Nation, One People: The USCIS Civics Test ...",...,Chapter 1: The U.S. Constitution,The U.S. Constitution,"In this chapter, you will learn about:\n\nThe ...",When was the U.S. Constitution written?,The U.S. Constitution was written in 1787.,0,1,2.580978,1.686085,1
16,1787,2.000000,stairs,i5elwnv4rzehfxkqz7gkybn7uu,the-u-s-constitution,The-US-Constitution-4445,True,0,2025-09-04T15:33:28.875Z,"One Nation, One People: The USCIS Civics Test ...",...,Chapter 1: The U.S. Constitution,The U.S. Constitution,"In this chapter, you will learn about:\n\nThe ...",When was the U.S. Constitution written?,The U.S. Constitution was written in 1787.,1,1,2.987468,2.697045,2
17,38 out of the 50 states.,2.862408,stairs,i6iirxwoh4e3bj4pkzlxyeobse,the-u-s-constitution,Changing-The-Constitution-4458,True,0,2025-09-08T07:39:24.647Z,"One Nation, One People: The USCIS Civics Test ...",...,Chapter 1: The U.S. Constitution,Changing The Constitution,The fifth section of the Constitution explains...,How many states must approve an amendment for ...,38 out of the 50 states.,1,1,2.861649,3.165299,2
18,38,2.279422,stairs,i6iirxwoh4e3bj4pkzlxyeobse,the-u-s-constitution,Changing-The-Constitution-4458,True,0,2025-09-08T07:33:18.272Z,"One Nation, One People: The USCIS Civics Test ...",...,Chapter 1: The U.S. Constitution,Changing The Constitution,The fifth section of the Constitution explains...,How many states must approve an amendment for ...,38 out of the 50 states.,1,1,2.277832,2.838821,2
19,38 states out of 50,2.773945,stairs,ci7hvzzqif5lhd4becodqngqye,the-u-s-constitution,Changing-The-Constitution-4458,True,0,2025-09-08T03:42:50.249Z,"One Nation, One People: The USCIS Civics Test ...",...,Chapter 1: The U.S. Constitution,Changing The Constitution,The fifth section of the Constitution explains...,How many states must approve an amendment for ...,38 out of the 50 states.,1,1,2.773114,2.878555,2
20,38 states,2.000000,stairs,wf5jicpb5uon42yzcgjpptpzyu,the-u-s-constitution,Changing-The-Constitution-4458,True,0,2025-09-04T22:07:35.581Z,"One Nation, One People: The USCIS Civics Test ...",...,Chapter 1: The U.S. Constitution,Changing The Constitution,The fifth section of the Constitution explains...,How many states must approve an amendment for ...,38 out of the 50 states.,1,1,2.661358,2.796786,2
21,"It reflects the ideas of self-government, whic...",3.520907,stairs,ci7hvzzqif5lhd4becodqngqye,the-u-s-constitution,We-The-People-4447,True,0,2025-09-08T03:37:11.907Z,"One Nation, One People: The USCIS Civics Test ...",...,Chapter 1: The U.S. Constitution,We The People,The beginning of the Constitution is called th...,What is the significance of the first three wo...,"The first three words, 'We the people', signif...",1,1,3.520004,3.759478,2
22,make the president follow the rule of law,1.000000,stairs,sievio4tkp2lqjadtpracywgtq,chapter-3-the-executive-branch,The-Executive-Branch-4752,True,0,2025-09-05T02:32:50.426Z,"One Nation, One People: The USCIS Civics Test ...",...,Chapter 3: The Executive Branch,The Executive Branch,"In this chapter, you will learn about:\n\nThe ...",What is the purpose of the Executive Branch ac...,The purpose of the Executive Branch is to prot...,1,0,2.856202,3.381410,1
23,house of rep and senate,2.000000,stairs,sievio4tkp2lqjadtpracywgtq,chapter-2-legislative-branch,The-Legislative-Branch-Congress-4729,True,0,2025-09-05T02:16:24.695Z,"One Nation, One People: The USCIS Civics Test ...",...,Chapter 2: The Legislative Branch,The Legislative Branch (Congress),"In this chapter, you will learn about:\n\nThe ...",What are the two parts of the U.S. Congress?,The House of Representatives and the Senate.,1,1,2.680958,2.303617,2
24,"They have a higher, bigger population so they ...",2.000000,stairs,wf5jicpb5uon42yzcgjpptpzyu,chapter-2-legislative-branch,The-House-of-Representatives-4730,True,0,2025-09-04T22:11:33.914Z,"One Nation, One People: The USCIS Civics Test ...",...,Chapter 2: The Legislative Branch,The House of Representatives,Voting Members of the House of Representatives...,Why do some states have more representatives i...,Because states that have more people have more...,1,1,3.128446,3.486940,2
25,judicial legsilative executive,2.000000,stairs,sievio4tkp2lqjadtpracywgtq,the-u-s-constitution,The-Federal-Government-4448,True,0,2025-09-04T22:09:57.638Z,"One Nation, One People: The USCIS Civics Test ...",...,Chapter 1: The U.S. Constitution,The Federal Government,The Three Branches of Government\n\nThe first ...,What are the three branches of the U.S. govern...,"The Legislative Branch, the Executive Branch, ...",1,1,2.929610,2.526067,2
26,justice legsilative executive,0.000000,stairs,sievio4tkp2lqjadtpracywgtq,the-u-s-constitution,The-Federal-Government-4448,True,0,2025-09-04T22:09:51.798Z,"One Nation, One People: The USCIS Civics Test ...",...,Chapter 1: The U.S. Constitution,The Federal Government,The Three Branches of Government\n\nThe first ...,What are the three branches of the U.S. govern...,"The Legislative Branch, the Executive Branch, ...",0,0,2.810153,2.491419,0
27,justice legal executive,1.000000,stairs,sievio4tkp2lqjadtpracywgtq,the-u-s-constitution,The-Federal-Government-4448,True,0,2025-09-04T22:09:17.405Z,"One Nation, One People: The USCIS Civics Test ...",...,Chapter 1: The U.S. Constitution,The Federal Government,The Three Branches of Government\n\nThe first ...,What are the three branches of the U.S. govern...,"The Legislative Branch, the Executive Branch, ...",1,0,3.271841,3.091077,1
28,justice legal exec,0.000000,stairs,sievio4tkp2lqjadtpracywgtq,the-u-s-constitution,The-Federal-Government-4448,True,0,2025-09-04T22:09:12.082Z,"One Nation, One People: The USCIS Civics Test ...",...,Chapter 1: The U.S. Constitution,The Federal Government,The Three Branches of Government\n\nThe first ...,What are the three branches of the U.S. govern...,"The Legislative Branch, the Executive Branch, ...",0,0,2.025746,1.864974,0
29,i dunno,0.000000,stairs,sievio4tkp2lqjadtpracywgtq,the-u-s-constitution,The-Federal-Government-4448,True,0,2025-09-04T22:09:01.628Z,"One Nation, One People: The USCIS Civics Test ...",...,Chapter 1: The U.S. Constitution,The Federal Government,The Three Branches of Government\n\nThe first ...,What are the three branches of the U.S. govern...,"The Legislative Branch, the Executive Branch, ...",0,0,1.546849,1.420386,0
30,asfkjh,0.000000,stairs,sievio4tkp2lqjadtpracywgtq,the-u-s-constitution,The-Federal-Government-4448,True,0,2025-09-04T22:08:58.391Z,"One Nation, One People: The USCIS Civics Test ...",...,Chapter 1: The U.S. Constitution,The Federal Government,The Three Branches of Government\n\nThe first ...,What are the three branches of the U.S. govern...,"The Legislative Branch, the Executive Branch, ...",0,0,1.458846,1.489535,0

In [9]:
df.to_csv("../../data/us-civics-trial-data-v2.csv")